Mayhem
bprof-projm/foerum pull request #144
Opened 2022-05-19 16:18 UTC by conoren

issue #143: Admin felületen jóváírás gomb irányítson át - done
not with iframe, but with new tab

2022-05-19 18:28 UTC, IIB3nceII requested changes

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Admin/Admin.tsx
> +      let tempContract = new ethers.Contract(contractAddress, abi, tempSigner);
These lets must be consts

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Admin/Admin.tsx
> +                //onClick={() => setActualPage(3)}
If we dont't use it, please remove

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Admin/Admin.tsx
> +                  transactions && transactions.length > 0 ? false : false //így nem lesz disabled
Please change this, this is awful. If I am not mistaken It should be disabled when transactions does not exist or the length is equal to 0

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Home/Header.tsx
> +  const [connStatus, setConnStatus] = useState<Boolean>(false);
These String and Boolean are classes, not types, use boolean and string instead.

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Home/Header.tsx
> +    let _connStatus = getConnStatus();
It must be const

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Home/Home.tsx
>            //console.log(res.data);
Remove this

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Home/Home.tsx
>            // console.log(res.data);
Remove this

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Home/Home.tsx
> +    let filteredBySubjects = topics;
?

2022-05-19 18:28 UTC, IIB3nceII commented on front-end/src/components/Home/Home.tsx
> +    let filteredByYear = filteredBySubjects;
?

2022-10-11 20:39 UTC, rolandbogdan commented
@IIB3nceII ez mikor lesz elfogadva? @conoren a conflictokat mikor oldod fel?

2022-10-13 18:34 UTC, belhart approved these changes
LGTM

2024-08-27 18:20 UTC, conoren commented on front-end/src/components/Admin/Admin.tsx
> +                  transactions && transactions.length > 0 ? false : false //így nem lesz disabled
anyad nem tudok kilepni

2024-08-27 19:06 UTC, IIB3nceII commented on front-end/src/components/Admin/Admin.tsx
> +                  transactions && transactions.length > 0 ? false : false //így nem lesz disabled
Ha feloldod a conflictokat segitek kilepni

2024-08-27 19:09 UTC, belhart commented on front-end/src/components/Admin/Admin.tsx
> +                  transactions && transactions.length > 0 ? false : false //így nem lesz disabled
Nyomj egy esc gombot, aztán egy olyat írj be hogy :q és már ki is léptél

2024-08-27 19:10 UTC, conoren commented
:q

2024-08-27 19:10 UTC, closed without merging

2024-08-27 19:11 UTC, conoren commented
yoho kész